version: "3.7"

services:
  db:
    image: mysql:8
    # Uncomment to use on an Apple m1 device
    # platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    cap_add:
      - SYS_NICE # fix warning "mbind: Operation not permitted"

  app:
    build:
      context: ./app
      args:
        TOMCAT_VERSION: "${TOMCAT_VERSION}"
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_USER: root # must match mysql image default root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 8081:8080
